### ISSUE TITLE
No data returned upon filtering using "Updateddate"

### ISSUE THREAD

**Issue by nmalde** [enverus-ea/enverus-developer-api#7]
Hello,

Filtering data using "Updateddate" via version 3 of the API gives returns the status code of 200 but doesn’t include any data.
 
Reproducer:

>>> import json
>>> import requests
>>> body = {"secretKey": "xxxxxxxxxxxxxxxxxxxxxxxxxx"}
>>> data = requests.post(
                          "https://api.enverus.com/v3/direct-access/tokens",
                          data=json.dumps(body),
                          headers={'content-type': 'application/json'
})

>>> headers = {'Accept': 'application/json', 'Authorization': "Bearer "+ json.loads(data.content)['token'] ,'X-Generate-Prev-Page-Links':'true'}

>>> rigs = requests.get("https://api.enverus.com/v3/direct-access/rigs?Updateddate=2021-10-31",headers=headers )
>>> print(rigs.content.decode("utf-8"))
 
This gives empty list as a response, We have encountered this issue with multiple dates.

Could you please help us filter data using update date such that we get:
  1. Records which were updated in last 1 month
  2. Records which were updated on a specific date

Thank you.

**Comment by henkhaus** [comment]
@nmalde 

I would actually use the enverus-developer-api library. The library abstracts complexity and uses the request library under the hood. 

[v3 Docs](https://github.com/enverus-ea/enverus-developer-api#developer-api---version-3)
[v3 Usage](https://github.com/enverus-ea/enverus-developer-api#usage)

to get rigs that have updated since Jan 1, 2022, you can format the query like this:

```
for row in d3.query('rigs', deleteddate='null', updateddate='ge(2022-01-01)'):
    print(row)
```

**Comment by nmalde** [comment]
Alright, I shall try this out and get back to you.  Since we already have a
significant chunk of code that uses requests to query data, would it be
possible for you to share a sample snippet for achieving the same using
requests (so as to avoid rewriting the code)?

**Comment by henkhaus** [comment]
@nmalde I would look at the source code in this repo for examples of how the library is leveraging requests.
