### ISSUE TITLE
Multi Parameters

### ISSUE THREAD

**Issue by esalmagul** [enverus-ea/enverus-developer-api#8]
Hi guys,

Is there a way to include multiple wells statuses and multiple counties for the code to download what is needed?

**Comment by henkhaus** [comment]
@esalmagul 

You can comma-separate or use the in() operator. See below:

`
print(d3.count('wells', deleteddate='null', ENVWellStatus='DRILLED'))

print(d3.count('wells', deleteddate='null', ENVWellStatus='DRILLED, COMPLETED'))

print(d3.count('wells', deleteddate='null', ENVWellStatus='in(DRILLED, COMPLETED)'))
`
